import Head from 'next/head'
import Nav from '../components/Nav'
import ArticleItem from '../components/ArticleItem'
import ArticleList from '../components/ArticleList'
import Footer from '../components/Footer'
import Box from '@mui/material/Box'

export default function Article({ article }) {
    return (
        <div>
            <Head>
                <title>Create Next App!!!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav />
                <ArticleItem article={article} main={true} />
                <Box pt={2} pb={2} sx={{
                    display: 'flex',
                    justifyContent: 'center',
                    backgroundColor: 'white'
                }}>
                </Box>
                <ArticleList articles={article.related} slug={article.slug} />
                <Footer />
            </main>
        </div>
    )
}

/* export const getServerSideProps = async (context) => {
    const res = await fetch(`https://www.moopio.com/${context.params.slug}.json`)
    const article = await res.json()

    return {
        props: {
            article,
        },
    }
} */

export async function getStaticProps({ params }) {
    const res = await fetch(`https://www.moopio.com/${params.slug}.json`)
    const article = await res.json()
    return {
        props: {
            article,
        },
        revalidate: 600,
    };
}

export async function getStaticPaths() {
    const res = await fetch('https://www.moopio.com/entry/show.json')
    const articles = await res.json()

    const paths = articles.map((article) => ({
        params: { slug: article.slug },
    }));

    return { paths, fallback: 'blocking' };
}