import Head from 'next/head'
import Button from '@mui/material/Button'
import Nav from '../components/Nav'
import { styled } from '@mui/material/styles';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
        <Nav />
      </main>
    </div>
  )
}
