import Head from 'next/head'
import Nav from '../components/Nav'
import ArticleList from '../components/ArticleList'
import MyBreadcrumbs from '../components/MyBreadcrumbs'
import Footer from '../components/Footer'

export default function Home({articles}) {
  return (
    <div>
      <Head>
        <title>Create Next App!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <main>
        <Nav />   
        <MyBreadcrumbs />
        <ArticleList articles={articles} />
        <Footer />
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://www.moopio.com/main/nuevos.json`)
  const articles = await res.json()
  
 
  return {
    props: {
      articles,
    },
  }
}
