import Head from 'next/head'
import Nav from '../components/Nav'
import ArticleList from '../components/ArticleList'
import Footer from '../components/Footer'
import Box from '@mui/material/Box'

export default function Home({ articles }) {
    return (
        <div>
            <Head>
                <title>Create Next App!!!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav />
                <ArticleList articles={articles} />
                <Box pt={2} pb={10} sx={{
                    display: 'flex',
                    justifyContent: 'center',
                    backgroundColor: 'red'
                }}>
                </Box>
                <Footer />
            </main>
        </div>
    )
}

export const getStaticProps = async () => {
    const res = await fetch(`https://www.moopio.com/entry/subiendo.json`)
    const articles = await res.json()

    return {
        props: {
            articles,
        },
    }
}
